// Shared vocabulary dictionary for ESL slide decks
// 6 languages: German (de), Spanish (es), French (fr), Italian (it), Portuguese (pt), Japanese (ja)
// Used in speaking decks with clickable vocab words

const vocabDictionary = {
  // ═══ MUSIC & ENTERTAINMENT ═══
  "concert": { example: "We went to a concert last weekend.", de: "Konzert", es: "concierto", fr: "concert", it: "concerto", pt: "concerto", ja: "コンサート" },
  "festival": { example: "The Salzburg Festival is famous.", de: "Festival", es: "festival", fr: "festival", it: "festival", pt: "festival", ja: "フェスティバル" },
  "live music": { example: "I prefer live music to recordings.", de: "Live-Musik", es: "música en vivo", fr: "musique en direct", it: "musica dal vivo", pt: "música ao vivo", ja: "ライブ音楽" },
  "to perform": { example: "She performs every Friday.", de: "auftreten", es: "actuar", fr: "se produire", it: "esibirsi", pt: "apresentar-se", ja: "演奏する" },
  "atmosphere": { example: "The atmosphere at the gig was amazing.", de: "Atmosphäre", es: "atmósfera", fr: "atmosphère", it: "atmosfera", pt: "atmosfera", ja: "雰囲気" },
  "crowd": { example: "The crowd was singing along.", de: "Menge", es: "multitud", fr: "foule", it: "folla", pt: "multidão", ja: "群衆" },
  "encore": { example: "The band played an encore.", de: "Zugabe", es: "bis", fr: "rappel", it: "bis", pt: "bis", ja: "アンコール" },
  "genre": { example: "What's your favourite music genre?", de: "Genre", es: "género", fr: "genre", it: "genere", pt: "gênero", ja: "ジャンル" },
  "to sing along": { example: "I like to sing along to my favourite songs.", de: "mitsingen", es: "cantar junto", fr: "chanter avec", it: "cantare insieme", pt: "cantar junto", ja: "一緒に歌う" },
  "ticket": { example: "I bought tickets in advance.", de: "Ticket", es: "entrada", fr: "billet", it: "biglietto", pt: "bilhete", ja: "チケット" },
  "venue": { example: "The venue was packed.", de: "Veranstaltungsort", es: "lugar", fr: "lieu", it: "locale", pt: "local", ja: "会場" },
  "memorable": { example: "It was a memorable experience.", de: "denkwürdig", es: "memorable", fr: "mémorable", it: "memorabile", pt: "memorável", ja: "忘れられない" },
  "unforgettable": { example: "The view was unforgettable.", de: "unvergesslich", es: "inolvidable", fr: "inoubliable", it: "indimenticabile", pt: "inesquecível", ja: "忘れられない" },
  "to influence": { example: "Who influences young people most?", de: "beeinflussen", es: "influir", fr: "influencer", it: "influenzare", pt: "influenciar", ja: "影響する" },
  "role model": { example: "Young people need role models.", de: "Vorbild", es: "modelo a seguir", fr: "modèle", it: "modello", pt: "modelo", ja: "ロールモデル" },
  "to achieve": { example: "I want to achieve my goals.", de: "erreichen", es: "lograr", fr: "atteindre", it: "raggiungere", pt: "alcançar", ja: "達成する" },
  "passion": { example: "She has a passion for music.", de: "Leidenschaft", es: "pasión", fr: "passion", it: "passione", pt: "paixão", ja: "情熱" },
  "dedication": { example: "His dedication is impressive.", de: "Hingabe", es: "dedicación", fr: "dévouement", it: "dedizione", pt: "dedicação", ja: "献身" },
  "talent": { example: "He has a natural talent.", de: "Talent", es: "talento", fr: "talent", it: "talento", pt: "talento", ja: "才能" },
  "spontaneous": { example: "It was a spontaneous decision.", de: "spontan", es: "espontáneo", fr: "spontané", it: "spontaneo", pt: "espontâneo", ja: "自発的" },
  "vibe": { example: "The vibe was incredible.", de: "Atmosphäre/Vibe", es: "ambiente", fr: "ambiance", it: "vibe", pt: "vibe", ja: "雰囲気" },
  "to resonate": { example: "That song resonates with me.", de: "widerhallen", es: "resonar", fr: "résonner", it: "risuonare", pt: "ressoar", ja: "響く" },
  "nostalgia": { example: "It fills me with nostalgia.", de: "Nostalgie", es: "nostalgia", fr: "nostalgie", it: "nostalgia", pt: "nostalgia", ja: "ノスタルジア" },
  "song": { example: "What is your favourite song?", de: "Lied", es: "canción", fr: "chanson", it: "canzone", pt: "canção", ja: "歌" },
  "to listen to": { example: "I listen to music every day.", de: "hören", es: "escuchar", fr: "écouter", it: "ascoltare", pt: "ouvir", ja: "聞く" },
  "to play an instrument": { example: "Are you learning to play a musical instrument?", de: "ein Instrument spielen", es: "tocar un instrumento", fr: "jouer d'un instrument", it: "suonare uno strumento", pt: "tocar um instrumento", ja: "楽器を弾く" },
  "musical instrument": { example: "I'm learning to play a musical instrument.", de: "Musikinstrument", es: "instrumento musical", fr: "instrument de musique", it: "strumento musicale", pt: "instrumento musical", ja: "楽器" },
  "taste": { example: "My music taste is varied.", de: "Geschmack/Vorliebe", es: "gusto", fr: "goût", it: "gusto", pt: "gosto", ja: "好み" },
  "to hear": { example: "Have you ever been to a concert before?", de: "hören", es: "oír", fr: "entendre", it: "sentire", pt: "ouvir", ja: "聞く" },
  "to attend": { example: "I'd love to attend that festival.", de: "besuchen", es: "asistir", fr: "assister à", it: "partecipare", pt: "participar", ja: "参加する" },

  // ═══ TRAVEL & TRANSPORT ═══
  "journey": { example: "Describe a journey you have been on.", de: "Reise", es: "viaje", fr: "voyage", it: "viaggio", pt: "viagem", ja: "旅" },
  "destination": { example: "What kind of tourist destinations do you prefer?", de: "Reiseziel", es: "destino turístico", fr: "destination touristique", it: "destinazione turistica", pt: "destino turístico", ja: "観光地" },
  "to travel": { example: "I love travelling abroad.", de: "reisen", es: "viajar", fr: "voyager", it: "viaggiare", pt: "viajar", ja: "旅行する" },
  "to book": { example: "I booked flights in advance.", de: "buchen", es: "reservar", fr: "réserver", it: "prenotare", pt: "reservar", ja: "予約する" },
  "accommodation": { example: "We found cheap accommodation.", de: "Unterkunft", es: "alojamiento", fr: "hébergement", it: "alloggio", pt: "alojamento", ja: "宿泊" },
  "flight": { example: "The flight was delayed.", de: "Flug", es: "vuelo", fr: "vol", it: "volo", pt: "voo", ja: "フライト" },
  "airport": { example: "We arrived at the airport early.", de: "Flughafen", es: "aeropuerto", fr: "aéroport", it: "aeroporto", pt: "aeroporto", ja: "空港" },
  "to pack": { example: "I always pack light.", de: "packen", es: "hacer las maletas", fr: "faire ses valises", it: "fare valigia", pt: "fazer as malas", ja: "荷物をまとめる" },
  "luggage": { example: "Don't forget your luggage.", de: "Gepäck", es: "equipaje", fr: "bagages", it: "bagagli", pt: "bagagem", ja: "荷物" },
  "passport": { example: "Do you have your passport?", de: "Reisepass", es: "pasaporte", fr: "passeport", it: "passaporto", pt: "passaporte", ja: "パスポート" },
  "visa": { example: "Do you need a visa?", de: "Visum", es: "visado", fr: "visa", it: "visto", pt: "visto", ja: "ビザ" },
  "to arrive": { example: "We arrived at the hotel.", de: "ankommen", es: "llegar", fr: "arriver", it: "arrivare", pt: "chegar", ja: "到着する" },
  "to depart": { example: "We depart tomorrow morning.", de: "abreisen", es: "partir", fr: "partir", it: "partire", pt: "partir", ja: "出発する" },
  "delay": { example: "There was a delay.", de: "Verspätung", es: "retraso", fr: "retard", it: "ritardo", pt: "atraso", ja: "遅延" },
  "to miss": { example: "Don't miss the train!", de: "verpassen", es: "perder", fr: "manquer", it: "perdere", pt: "perder", ja: "乗り遅れる" },
  "platform": { example: "The train is on platform 3.", de: "Gleis/Bahnsteig", es: "andén", fr: "quai", it: "binario", pt: "plataforma", ja: "ホーム" },
  "scenery": { example: "I enjoy the scenery through the window.", de: "Landschaft", es: "paisaje", fr: "paysage", it: "paesaggio", pt: "paisagem", ja: "景色" },
  "to explore": { example: "I love exploring new places.", de: "erkunden", es: "explorar", fr: "explorer", it: "esplorare", pt: "explorar", ja: "探索する" },
  "to recommend": { example: "I'd recommend visiting the old town.", de: "empfehlen", es: "recomendar", fr: "recommander", it: "raccomandare", pt: "recomendar", ja: "お勧めする" },
  "souvenir": { example: "I bought a souvenir.", de: "Andenken", es: "recuerdo", fr: "souvenir", it: "ricordo", pt: "lembrança", ja: "お土産" },
  "to get lost": { example: "I got lost in the city.", de: "sich verlaufen", es: "perderse", fr: "se perdre", it: "perdersi", pt: "perder-se", ja: "道に迷う" },
  "map": { example: "Do you have a map?", de: "Karte", es: "mapa", fr: "carte", it: "mappa", pt: "mapa", ja: "地図" },
  "guidebook": { example: "I read the guidebook.", de: "Reiseführer", es: "guía", fr: "guide", it: "guida", pt: "guia", ja: "ガイドブック" },
  "to take photos": { example: "I took many photos.", de: "Fotos machen", es: "tomar fotos", fr: "prendre des photos", it: "scattare foto", pt: "tirar fotos", ja: "写真を撮る" },
  "scenic": { example: "The view was scenic.", de: "malerisch", es: "pintoresco", fr: "panoramique", it: "panoramico", pt: "panorâmico", ja: "風光明媚な" },
  "tourist": { example: "It's a popular tourist spot.", de: "Tourist", es: "turista", fr: "touriste", it: "turista", pt: "turista", ja: "観光客" },
  "local": { example: "Ask a local for recommendations.", de: "Einheimischer", es: "local", fr: "local", it: "locale", pt: "local", ja: "地元の人" },
  "to book in advance": { example: "Book in advance for better prices.", de: "im Voraus buchen", es: "reservar con anticipación", fr: "réserver à l'avance", it: "prenotare in anticipo", pt: "reservar com antecedência", ja: "事前に予約する" },

  // ═══ WORK & CAREER ═══
  "job": { example: "What's your job?", de: "Beruf/Job", es: "trabajo", fr: "emploi", it: "lavoro", pt: "emprego", ja: "仕事" },
  "career": { example: "She has a successful career.", de: "Karriere", es: "carrera", fr: "carrière", it: "carriera", pt: "carreira", ja: "キャリア" },
  "to work": { example: "I work in marketing.", de: "arbeiten", es: "trabajar", fr: "travailler", it: "lavorare", pt: "trabalhar", ja: "働く" },
  "colleague": { example: "My colleague is very helpful.", de: "Kollege", es: "colega", fr: "collègue", it: "collega", pt: "colega", ja: "同僚" },
  "boss": { example: "My boss is understanding.", de: "Chef", es: "jefe", fr: "patron", it: "capo", pt: "chefe", ja: "上司" },
  "meeting": { example: "We have a meeting at 10.", de: "Meeting/Sitzung", es: "reunión", fr: "réunion", it: "riunione", pt: "reunião", ja: "会議" },
  "presentation": { example: "I gave a presentation.", de: "Präsentation", es: "presentación", fr: "présentation", it: "presentazione", pt: "apresentação", ja: "プレゼンテーション" },
  "to present": { example: "She presented the new project.", de: "präsentieren", es: "presentar", fr: "présenter", it: "presentare", pt: "apresentar", ja: "発表する" },
  "salary": { example: "The salary is important to me.", de: "Gehalt", es: "salario", fr: "salaire", it: "stipendio", pt: "salário", ja: "給料" },
  "to earn": { example: "He earns a good salary.", de: "verdienen", es: "ganar", fr: "gagner", it: "guadagnare", pt: "ganhar", ja: "稼ぐ" },
  "qualification": { example: "What qualifications do you need?", de: "Qualifikation", es: "cualificación", fr: "qualification", it: "qualifica", pt: "qualificação", ja: "資格" },
  "experience": { example: "Do you have experience?", de: "Erfahrung", es: "experiencia", fr: "expérience", it: "esperienza", pt: "experiência", ja: "経験" },
  "skill": { example: "Communication skills are essential.", de: "Fähigkeit", es: "habilidad", fr: "compétence", it: "abilità", pt: "habilidade", ja: "スキル" },
  "to apply": { example: "I applied for the job.", de: "sich bewerben", es: "solicitar", fr: "postuler", it: "candidarsi", pt: "candidatar-se", ja: "応募する" },
  "resume": { example: "Send your resume.", de: "Lebenslauf", es: "currículum", fr: "CV", it: "curriculum", pt: "currículo", ja: "履歴書" },
  "interview": { example: "I have an interview tomorrow.", de: "Vorstellungsgespräch", es: "entrevista", fr: "entretien", it: "colloquio", pt: "entrevista", ja: "面接" },
  "to promote": { example: "He got promoted last year.", de: "befördert werden", es: "ser ascendido", fr: "être promu", it: "essere promossi", pt: "ser promovido", ja: "昇進する" },
  "responsibility": { example: "What responsibilities do you have?", de: "Verantwortung", es: "responsabilidad", fr: "responsabilité", it: "responsabilità", pt: "responsabilidade", ja: "責任" },
  "to manage": { example: "She manages a team of 10.", de: "leiten", es: "gestionar", fr: "gérer", it: "gestire", pt: "gerir", ja: "管理する" },
  "teamwork": { example: "Teamwork is essential.", de: "Teamarbeit", es: "trabajo en equipo", fr: "travail d'équipe", it: "lavoro di squadra", pt: "trabalho em equipe", ja: "チームワーク" },
  "deadline": { example: "We have a tight deadline.", de: "Frist", es: "plazo", fr: "délai", it: "scadenza", pt: "prazo", ja: "締め切り" },
  "to meet a deadline": { example: "Can we meet the deadline?", de: "eine Frist einhalten", es: "cumplir el plazo", fr: "respecter le délai", it: "rispettere la scadenza", pt: "cumprir o prazo", ja: "締め切りを守る" },
  "project": { example: "We're working on a new project.", de: "Projekt", es: "proyecto", fr: "projet", it: "progetto", pt: "projeto", ja: "プロジェクト" },
  "to collaborate": { example: "We collaborate across departments.", de: "zusammenarbeiten", es: "colaborar", fr: "collaborer", it: "collaborare", pt: "colaborar", ja: "協力する" },

  // ═══ ENVIRONMENT & NATURE ═══
  "environment": { example: "We should protect the environment.", de: "Umwelt", es: "medio ambiente", fr: "environnement", it: "ambiente", pt: "meio ambiente", ja: "環境" },
  "to protect": { example: "How can we protect the environment?", de: "schützen", es: "proteger", fr: "protéger", it: "proteggere", pt: "proteger", ja: "守る" },
  "pollution": { example: "Air pollution is a problem.", de: "Verschmutzung", es: "contaminación", fr: "pollution", it: "inquinamento", pt: "poluição", ja: "汚染" },
  "climate change": { example: "Climate change affects everyone.", de: "Klimawandel", es: "cambio climático", fr: "changement climatique", it: "cambiamento climatico", pt: "mudança climática", ja: "気候変動" },
  "to recycle": { example: "We should recycle more.", de: "recyceln", es: "reciclar", fr: "recycler", it: "riciclare", pt: "reciclar", ja: "リサイクルする" },
  "waste": { example: "Reduce waste.", de: "Abfall", es: "residuos", fr: "déchets", it: "rifiuti", pt: "resíduos", ja: "廃棄物" },
  "sustainable": { example: "Choose sustainable options.", de: "nachhaltig", es: "sostenible", fr: "durable", it: "sostenibile", pt: "sustentável", ja: "持続可能な" },
  "renewable": { example: "Renewable energy is the future.", de: "erneuerbar", es: "renovable", fr: "renouvelable", it: "rinnovabile", pt: "renovável", ja: "再生可能な" },
  "to conserve": { example: "Conserve water.", de: "schonen", es: "conservar", fr: "conserver", it: "conservare", pt: "conservar", ja: "節約する" },
  "endangered": { example: "Protect endangered species.", de: "gefährdet", es: "en peligro", fr: "en danger", it: "in via di estinzione", pt: "em perigo", ja: "絶滅危惧種" },
  "species": { example: "Many species are endangered.", de: "Art", es: "especie", fr: "espèce", it: "specie", pt: "espécie", ja: "種" },
  "habitat": { example: "Protect natural habitats.", de: "Lebensraum", es: "hábitat", fr: "habitat", it: "habitat", pt: "habitat", ja: "生息地" },
  "to plant": { example: "We planted trees.", de: "pflanzen", es: "plantar", fr: "planter", it: "piantare", pt: "plantar", ja: "植える" },
  "to hike": { example: "I love hiking in the mountains.", de: "wandern", es: "hacer senderismo", fr: "faire de la randonnée", it: "fare escursionismo", pt: "fazer trilhas", ja: "ハイキングする" },
  "trail": { example: "The hiking trail was beautiful.", de: "Weg/Pfad", es: "sendero", fr: "sentier", it: "sentiero", pt: "trilha", ja: "トレイル" },
  "view": { example: "The view was breathtaking.", de: "Aussicht", es: "vista", fr: "vue", it: "vista", pt: "vista", ja: "景色" },
  "mountain": { example: "We climbed the mountain.", de: "Berg", es: "montaña", fr: "montagne", it: "montagna", pt: "montanha", ja: "山" },
  "forest": { example: "The forest is dense.", de: "Wald", es: "bosque", fr: "forêt", it: "foresta", pt: "floresta", ja: "森" },
  "river": { example: "The river flows through the valley.", de: "Fluss", es: "río", fr: "rivière", it: "fiume", pt: "rio", ja: "川" },
  "ocean": { example: "The ocean is vast.", de: "Ozean", es: "océano", fr: "océan", it: "oceano", pt: "oceano", ja: "海" },
  "weather": { example: "How's the weather today?", de: "Wetter", es: "tiempo", fr: "temps", it: "tempo", pt: "tempo", ja: "天気" },
  "season": { example: "My favourite season is summer.", de: "Jahreszeit", es: "estación", fr: "saison", it: "stagione", pt: "estação", ja: "季節" },
  "temperature": { example: "The temperature is rising.", de: "Temperatur", es: "temperatura", fr: "température", it: "temperatura", pt: "temperatura", ja: "気温" },

  // ═══ HEALTH & LIFESTYLE ═══
  "health": { example: "Good health is important.", de: "Gesundheit", es: "salud", fr: "santé", it: "salute", pt: "saúde", ja: "健康" },
  "healthy": { example: "I have a healthy diet.", de: "gesund", es: "saludable", fr: "sain", it: "salutare", pt: "saudável", ja: "健康的な" },
  "diet": { example: "A balanced diet is important.", de: "Ernährung", es: "dieta", fr: "régime alimentaire", it: "dieta", pt: "dieta", ja: "食事" },
  "exercise": { example: "I do exercise every day.", de: "Sport/Bewegung", es: "ejercicio", fr: "exercice", it: "esercizio", pt: "exercício", ja: "運動" },
  "to work out": { example: "I work out three times a week.", de: "trainieren", es: "entrenar", fr: "s'entraîner", it: "allenarsi", pt: "treinar", ja: "トレーニングする" },
  "fitness": { example: "Fitness is important to me.", de: "Fitness", es: "forma física", fr: "forme physique", it: "fitness", pt: "fitness", ja: "フィットネス" },
  "to sleep": { example: "I sleep 8 hours a night.", de: "schlafen", es: "dormir", fr: "dormir", it: "dormire", pt: "dormir", ja: "寝る" },
  "stress": { example: "Stress affects health.", de: "Stress", es: "estrés", fr: "stress", it: "stress", pt: "estresse", ja: "ストレス" },
  "to relax": { example: "I need to relax.", de: "sich entspannen", es: "relajarse", fr: "se détendre", it: "rilassarsi", pt: "relaxar", ja: "リラックスする" },
  "wellness": { example: "Wellness is a priority.", de: "Wellness", es: "bienestar", fr: "bien-être", it: "benessere", pt: "bem-estar", ja: "ウェルネス" },
  "habit": { example: "Bad habits are hard to break.", de: "Gewohnheit", es: "hábito", fr: "habitude", it: "abitudine", pt: "hábito", ja: "習慣" },
  "routine": { example: "I have a daily routine.", de: "Routine/Tagesablauf", es: "rutina", fr: "routine", it: "routine", pt: "rotina", ja: "ルーティン" },
  "to change": { example: "I want to change my habits.", de: "ändern", es: "cambiar", fr: "changer", it: "cambiare", pt: "mudar", ja: "変える" },
  "to improve": { example: "I want to improve my lifestyle.", de: "verbessern", es: "mejorar", fr: "améliorer", it: "migliorare", pt: "melhorar", ja: "改善する" },
  "energy": { example: "I have more energy now.", de: "Energie", es: "energía", fr: "énergie", it: "energia", pt: "energia", ja: "エネルギー" },
  "to feel": { example: "I feel great.", de: "sich fühlen", es: "sentirse", fr: "se sentir", it: "sentirsi", pt: "sentir-se", ja: "感じる" },

  // ═══ TECHNOLOGY & SOCIAL MEDIA ═══
  "technology": { example: "Technology changes our lives.", de: "Technologie", es: "tecnología", fr: "technologie", it: "tecnologia", pt: "tecnologia", ja: "技術" },
  "social media": { example: "I use social media daily.", de: "Soziale Medien", es: "redes sociales", fr: "réseaux sociaux", it: "social media", pt: "redes sociais", ja: "ソーシャルメディア" },
  "internet": { example: "The internet is essential.", de: "Internet", es: "internet", fr: "internet", it: "internet", pt: "internet", ja: "インターネット" },
  "website": { example: "Visit our website.", de: "Webseite", es: "sitio web", fr: "site web", it: "sito web", pt: "site", ja: "ウェブサイト" },
  "app": { example: "Download the app.", de: "App", es: "aplicación", fr: "application", it: "applicazione", pt: "aplicativo", ja: "アプリ" },
  "to download": { example: "Download the file.", de: "herunterladen", es: "descargar", fr: "télécharger", it: "scaricare", pt: "baixar", ja: "ダウンロードする" },
  "to upload": { example: "Upload your photos.", de: "hochladen", es: "subir", fr: "téléverser", it: "caricare", pt: "enviar", ja: "アップロードする" },
  "screen": { example: "I spend too much time on screens.", de: "Bildschirm", es: "pantalla", fr: "écran", it: "schermo", pt: "tela", ja: "画面" },
  "device": { example: "My phone is a useful device.", de: "Gerät", es: "dispositivo", fr: "appareil", it: "dispositivo", pt: "dispositivo", ja: "デバイス" },
  "to charge": { example: "I need to charge my phone.", de: "aufladen", es: "cargar", fr: "charger", it: "ricaricare", pt: "carregar", ja: "充電する" },
  "battery": { example: "My battery is low.", de: "Batterie", es: "batería", fr: "batterie", it: "batteria", pt: "bateria", ja: "バッテリー" },
  "to connect": { example: "Connect to the WiFi.", de: "verbinden", es: "conectar", fr: "se connecter", it: "connettersi", pt: "conectar", ja: "接続する" },
  "password": { example: "Enter your password.", de: "Passwort", es: "contraseña", fr: "mot de passe", it: "password", pt: "senha", ja: "パスワード" },
  "to search": { example: "Search for information.", de: "suchen", es: "buscar", fr: "chercher", it: "cercare", pt: "procurar", ja: "検索する" },
  "information": { example: "I need more information.", de: "Information", es: "información", fr: "information", it: "informazione", pt: "informação", ja: "情報" },
  "to share": { example: "Share this post.", de: "teilen", es: "compartir", fr: "partager", it: "condividere", pt: "compartilhar", ja: "共有する" },
  "to post": { example: "I posted a photo.", de: "posten", es: "publicar", fr: "publier", it: "pubblicare", pt: "publicar", ja: "投稿する" },
  "comment": { example: "Leave a comment.", de: "Kommentar", es: "comentario", fr: "commentaire", it: "commento", pt: "comentário", ja: "コメント" },
  "to scroll": { example: "I scroll through feeds all day.", de: "scrollen", es: "desplazarse", fr: "faire défiler", it: "scorrere", pt: "rolar", ja: "スクロールする" },
  "notification": { example: "I get too many notifications.", de: "Benachrichtigung", es: "notificación", fr: "notification", it: "notifica", pt: "notificação", ja: "通知" },

  // ═══ GENERAL USEFUL WORDS ═══
  "to agree": { example: "I agree with you.", de: "zustimmen", es: "estar de acuerdo", fr: "être d'accord", it: "essere d'accordo", pt: "concordar", ja: "同意する" },
  "to disagree": { example: "I disagree.", de: "widersprechen", es: "no estar de acuerdo", fr: "ne pas être d'accord", it: "non essere d'accordo", pt: "discordar", ja: "反対する" },
  "opinion": { example: "What's your opinion?", de: "Meinung", es: "opinión", fr: "avis", it: "opinione", pt: "opinião", ja: "意見" },
  "to think": { example: "I think it's a good idea.", de: "denken", es: "pensar", fr: "penser", it: "pensare", pt: "pensar", ja: "思う" },
  "to believe": { example: "I believe in hard work.", de: "glauben", es: "creer", fr: "croire", it: "credere", pt: "acreditar", ja: "信じる" },
  "to understand": { example: "Do you understand?", de: "verstehen", es: "entender", fr: "comprendre", it: "capire", pt: "entender", ja: "理解する" },
  "to explain": { example: "Can you explain that?", de: "erklären", es: "explicar", fr: "expliquer", it: "spiegare", pt: "explicar", ja: "説明する" },
  "to describe": { example: "Describe what you see.", de: "beschreiben", es: "describir", fr: "décrire", it: "descrivere", pt: "descrever", ja: "説明する" },
  "to compare": { example: "Compare the two options.", de: "vergleichen", es: "comparar", fr: "comparer", it: "confrontare", pt: "comparar", ja: "比較する" },
  "to recommend": { example: "I'd recommend this restaurant.", de: "empfehlen", es: "recomendar", fr: "recommander", it: "raccomandare", pt: "recomendar", ja: "お勧めする" },
  "to suggest": { example: "Can you suggest something?", de: "vorschlagen", es: "sugerir", fr: "suggérer", it: "suggerire", pt: "sugerir", ja: "提案する" },
  "to decide": { example: "I decided to study harder.", de: "sich entscheiden", es: "decidir", fr: "décider", it: "decidere", pt: "decidir", ja: "決める" },
  "to plan": { example: "I'm planning a trip.", de: "planen", es: "planear", fr: "planifier", it: "pianificare", pt: "planejar", ja: "計画する" },
  "to hope": { example: "I hope to pass the exam.", de: "hoffen", es: "esperar", fr: "espérer", it: "sperare", pt: "esperar", ja: "望む" },
  "to want": { example: "I want to improve.", de: "wollen", es: "querer", fr: "vouloir", it: "volere", pt: "querer", ja: "欲しい" },
  "to need": { example: "I need more practice.", de: "brauchen", es: "necesitar", fr: "avoir besoin de", it: "avere bisogno di", pt: "precisar", ja: "必要とする" },
  "to try": { example: "I'll try my best.", de: "versuchen", es: "intentar", fr: "essayer", it: "provare", pt: "tentar", ja: "試す" },
  "to learn": { example: "I'm learning English.", de: "lernen", es: "aprender", fr: "apprendre", it: "imparare", pt: "aprender", ja: "学ぶ" },
  "to practice": { example: "Practice makes perfect.", de: "üben/trainieren", es: "practicar", fr: "pratiquer", it: "praticare", pt: "praticar", ja: "練習する" },
  "to remember": { example: "Remember to study.", de: "sich erinnern", es: "recordar", fr: "se souvenir", it: "ricordare", pt: "lembrar", ja: "覚える" },
  "to forget": { example: "Don't forget your book.", de: "vergessen", es: "olvidar", fr: "oublier", it: "dimenticare", pt: "esquecer", ja: "忘れる" },
  "important": { example: "It's important to practice.", de: "wichtig", es: "importante", fr: "important", it: "importante", pt: "importante", ja: "重要な" },
  "necessary": { example: "Is it necessary?", de: "notwendig", es: "necesario", fr: "nécessaire", it: "necessario", pt: "necessário", ja: "必要な" },
  "possible": { example: "Is it possible?", de: "möglich", es: "posible", fr: "possible", it: "possibile", pt: "possível", ja: "可能な" },
  "different": { example: "It's completely different.", de: "anders", es: "diferente", fr: "différent", it: "diverso", pt: "diferente", ja: "違う" },
  "similar": { example: "We have similar interests.", de: "ähnlich", es: "similar", fr: "similaire", it: "simile", pt: "similar", ja: "似た" },
  "the same": { example: "It's the same thing.", de: "das Gleiche", es: "lo mismo", fr: "la même chose", it: "la stessa cosa", pt: "a mesma coisa", ja: "同じ" },
  "because": { example: "I stayed home because I was tired.", de: "weil", es: "porque", fr: "parce que", it: "perché", pt: "porque", ja: "なぜなら" },
  "so": { example: "I was tired, so I stayed home.", de: "also", es: "así que", fr: "donc", it: "quindi", pt: "então", ja: "だから" },
  "but": { example: "I wanted to go, but I was tired.", de: "aber", es: "pero", fr: "mais", it: "ma", pt: "mas", ja: "しかし" },
  "although": { example: "Although it was late, we continued.", de: "obwohl", es: "aunque", fr: "bien que", it: "anche se", pt: "embora", ja: "～にもかかわらず" },
  "however": { example: "It was hard. However, I succeeded.", de: "jedoch", es: "sin embargo", fr: "cependant", it: "tuttavia", pt: "no entanto", ja: "しかしながら" },
  "therefore": { example: "I studied hard. Therefore, I passed.", de: "deshalb", es: "por lo tanto", fr: "par conséquent", it: "pertanto", pt: "portanto", ja: "したがって" },
  "also": { example: "I also like hiking.", de: "auch", es: "también", fr: "aussi", it: "anche", pt: "também", ja: "も" },
  "too": { example: "I want to come too.", de: "auch", es: "también", fr: "aussi", it: "anche", pt: "também", ja: "も" },
  "very": { example: "It's very important.", de: "sehr", es: "muy", fr: "très", it: "molto", pt: "muito", ja: "とても" },
  "really": { example: "I really enjoy it.", de: "wirklich", es: "realmente", fr: "vraiment", it: "davvero", pt: "realmente", ja: "本当に" },
  "quite": { example: "It's quite difficult.", de: "ziemlich", es: "bastante", fr: "assez", it: "abbastanza", pt: "bastante", ja: "かなり" },
  "a lot": { example: "I learned a lot.", de: "viel", es: "mucho", fr: "beaucoup", it: "molto", pt: "muito", ja: "たくさん" },
};
